name: Build Padavan

on: 
  workflow_dispatch:
    inputs:
      build_config:
        default: 'PSG1218_nano'
      build_config_4.4:
        default: 'K2P_nano'  

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        sudo git clone --depth=1 https://github.com/hanwckf/padavan-4.4.git /opt/padavan-4.4
        cd /opt/padavan-4.4/toolchain-mipsel
        sudo sh dl_toolchain.sh
        sudo git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sudo sh dl_toolchain.sh
        sudo mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: ${{ github.event.inputs.build_config }}
        TNAME4_4: ${{ github.event.inputs.build_config_4.4 }}
      run: |
        cd /opt/padavan-4.4/trunk
        if [ ! -f configs/templates/$TNAME4_4.config ] ; then
        echo "configs/templates/$TNAME4_4.config not found "
        exit 1
        else
        cp -f configs/templates/$TNAME4_4.config .config
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME4_4 0
        sudo mv -f images/*.trx /opt/images/
        fi
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        else
        cp -f configs/templates/$TNAME.config .config
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
        fi
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
